#!/bin/bash

mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_PEDIDOS_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_PEDIDOS_USER}'@'%' IDENTIFIED BY '${MYSQL_PEDIDOS_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_PEDIDOS_DATABASE}.* TO '${MYSQL_PEDIDOS_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${MYSQL_PAGAMENTOS_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_PAGAMENTOS_USER}'@'%' IDENTIFIED BY '${MYSQL_PAGAMENTOS_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_PAGAMENTOS_DATABASE}.* TO '${MYSQL_PAGAMENTOS_USER}'@'%';

FLUSH PRIVILEGES;
EOF